INSERT INTO java_message (text, topic) VALUES
                                           ('В чем преимущества Spring?', 'SPRING'),
                                           ('Что такое файл конфигурации для Spring?', 'SPRING'),
                                           ('Каковы различные модули Spring Framework?', 'SPRING'),
                                           ('Каковы различные компоненты приложения Spring?', 'SPRING'),
                                           ('Что такое внедрение зависимостей?', 'SPRING'),
                                           ('Что такое Spring IoC контейнер?', 'SPRING'),
                                           ('Каковы типы IoC?', 'SPRING'),
                                           ('Что такое Аспектно-ориентированное программирование (AOP)?', 'SPRING'),
                                           ('Что такое Spring Bean?', 'SPRING'),
                                           ('Каковы общие реализации ApplicationContext?', 'SPRING'),
                                           ('В чем разница между BeanFactory и ApplicationContext?', 'SPRING'),
                                           ('Как вы добавляете компонент в Spring?', 'SPRING'),
                                           ('Какие области Beans поддерживает Spring?', 'SPRING'),
                                           ('Каковы этапы жизненного цикла компонента?', 'SPRING'),
                                           ('Объясните внутреннюю часть bean в Spring.', 'SPRING'),
                                           ('Что такое автоматическая проводка bean?', 'SPRING'),
                                           ('Как вы можете внедрить коллекции Java в Spring?', 'SPRING'),
                                           ('Что такое Joinpoint?', 'SPRING'),
                                           ('Что такое Advice в Spring?', 'SPRING'),
                                           ('Каковы типы рекомендаций для структуры Spring?', 'SPRING'),
                                           ('Что такое Weaving?', 'SPRING'),
                                           ('Опишите поддержку Spring DAO.', 'SPRING'),
                                           ('Что такое Spring Boot?', 'SPRING'),
                                           ('Что такое Реактивное программирование?', 'SPRING'),
                                           ('Что такое Spring WebFlux?', 'SPRING'),
                                           ('Может ли Spring Boot разрешить Spring MVC или Spring WebFlux в одном и том же приложении?', 'SPRING'),
                                           ('Сравните BeanFactory, Factory bean, ApplicationContext.', 'SPRING'),
                                           ('Опишите самые распространенные аннотации Spring.', 'SPRING'),
                                           ('В чем разница между IoC (Inversion of Control) и ApplicationContext?', 'SPRING'),
                                           ('В чем разница между Filters, Listeners и Interceptors?', 'SPRING'),
                                           ('Что можете рассказать про Form Binding?', 'SPRING'),
                                           ('Где должны располагаться статические (css, js, html) ресурсы в Spring MVC приложении?', 'SPRING'),
                                           ('Что такое ViewResolver в Spring?', 'SPRING'),
                                           ('Best Practices в Spring Framework.', 'SPRING'),
                                           ('В чем основная разница между Spring и Spring Boot?', 'SPRING');