INSERT INTO java_message (text, topic) VALUES
                                           ('Что такое Hibernate Framework?', 'HIBERNATE'),
                                           ('Какие важные преимущества дает использование Hibernate Framework?', 'HIBERNATE'),
                                           ('Какие преимущества Hibernate над JDBC?', 'HIBERNATE'),
                                           ('Назовите некоторые важные интерфейсы Hibernate.', 'HIBERNATE'),
                                           ('Что такое конфигурационный файл Hibernate?', 'HIBERNATE'),
                                           ('Назовите некоторые важные аннотации, используемые для отображения в Hibernate.', 'HIBERNATE'),
                                           ('Что вы знаете о Hibernate SessionFactory и как его сконфигурировать?', 'HIBERNATE'),
                                           ('Является ли Hibernate SessionFactory потокобезопасным?', 'HIBERNATE'),
                                           ('Как получить Hibernate Session и что это такое?', 'HIBERNATE'),
                                           ('Является ли Hibernate Session потокобезопасным?', 'HIBERNATE'),
                                           ('В чем разница между openSession и getCurrentSession?', 'HIBERNATE'),
                                           ('Какая разница между методами Hibernate Session get() и load()?', 'HIBERNATE'),
                                           ('Что вы знаете о кэшировании в Hibernate? Объясните понятие кэш первого уровня в Hibernate.', 'HIBERNATE'),
                                           ('Как настроить кэш второго уровня в Hibernate с помощью EHCache?', 'HIBERNATE'),
                                           ('Какие существуют различные состояния у entity bean?', 'HIBERNATE'),
                                           ('Как используется вызов метода Hibernate Session merge()?', 'HIBERNATE'),
                                           ('В чем разница между Hibernate save(), saveOrUpdate() и persist()?', 'HIBERNATE'),
                                           ('Что произойдет, если будет отсутствовать конструктор без аргументов у Entity Bean?', 'HIBERNATE'),
                                           ('В чем разница между sorted collection и ordered collection? Какая из них лучше?', 'HIBERNATE'),
                                           ('Какие типы коллекций в Hibernate вы знаете?', 'HIBERNATE'),
                                           ('Как реализованы Join’ы Hibernate?', 'HIBERNATE'),
                                           ('Почему мы не должны делать Entity class как final?', 'HIBERNATE'),
                                           ('Что вы знаете о HQL и какие его преимущества?', 'HIBERNATE'),
                                           ('Что такое Query Cache в Hibernate?', 'HIBERNATE'),
                                           ('Можем ли мы выполнить нативный запрос SQL (native SQL) в Hibernate?', 'HIBERNATE'),
                                           ('Назовите преимущества поддержки нативного SQL в Hibernate.', 'HIBERNATE'),
                                           ('Что такое Named SQL Query?', 'HIBERNATE'),
                                           ('Расскажите о преимуществах использования Hibernate Criteria API.', 'HIBERNATE'),
                                           ('Как логировать созданные Hibernate SQL запросы в лог-файлы?', 'HIBERNATE'),
                                           ('Что вы знаете о Hibernate прокси и как это помогает в ленивой загрузке (lazy load)?', 'HIBERNATE'),
                                           ('Как реализованы отношения в Hibernate?', 'HIBERNATE'),
                                           ('Как управлять транзакциями с помощью Hibernate?', 'HIBERNATE'),
                                           ('Что такое каскадные связи (обновления) и какие каскадные типы есть в Hibernate?', 'HIBERNATE'),
                                           ('Как добавить логирование log4j в Hibernate приложение?', 'HIBERNATE'),
                                           ('Как использовать JNDI DataSource сервера приложений с Hibernate Framework?', 'HIBERNATE'),
                                           ('Как интегрировать Hibernate и Spring?', 'HIBERNATE'),
                                           ('Что вы знаете о классе HibernateTemplate?', 'HIBERNATE'),
                                           ('Как интегрировать Hibernate с Servlet или Struts2 веб приложением?', 'HIBERNATE'),
                                           ('Какие паттерны применяются в Hibernate?', 'HIBERNATE'),
                                           ('Расскажите о Hibernate Validator Framework.', 'HIBERNATE'),
                                           ('Какие преимущества дает использование плагина Hibernate Tools Eclipse?', 'HIBERNATE'),
                                           ('Best Practices в Hibernate.', 'HIBERNATE'),
                                           ('Какие есть кэши в Hibernate и какие работают по умолчанию?', 'HIBERNATE'),
                                           ('Чем отличается Lazy от Eager в Hibernate?', 'HIBERNATE'),
                                           ('Что такое "проблема N+1 запроса" при использовании Hibernate? Когда возникает? Как решить? Как обнаружить?', 'HIBERNATE'),
                                           ('Как описать составной ключ при использовании Hibernate?', 'HIBERNATE'),
                                           ('Как можно отобразить наследование на БД с помощью JPA (Hibernate)?', 'HIBERNATE'),
                                           ('Какие бывают типы индексов в БД и как они устроены под капотом? Что такое индекс вообще?', 'HIBERNATE'),
                                           ('В чем разница между оптимистической и пессимистической блокировками?', 'HIBERNATE');